### ISSUE TITLE
Rifle Sights

### ISSUE THREAD

**Issue by Beezle9891** [jekyllgrim/Beautiful-Doom#1]
The iron sights with the Assault Rifle don't line up with the crosshairs. As long as you have crosshair enabled in the hud you can still see where the bullets should go, however without it enabled, the bullets seem to go about 2 feet above where iron sights are aimed.
![bdoom rifle modern set](https://user-images.githubusercontent.com/45604754/49462662-789fb180-f7ab-11e8-9684-7beb9a35ab5b.PNG)

**Comment by jekyllgrim** [comment]
The iron sights on the sprite are drawn in perspective, not aligned, so they're not aimed directly at where the sight ends on the screen (that's why you can see the length of the barrel). In other words, bullets do fly where they're supposed to (along with the imaginary direction the barrel is pointing at).

Whereas in modern games iron sights are used as actual sights and are thus indeed often aligned at the center, here's it's just a visual effect to signify that accuracy is increased. Actual iron sights IMO would take up too much space. The use of regular crosshair is indeed intended and implied.
