### ISSUE TITLE
Super Shotgun alt fire gibbing

### ISSUE THREAD

**Issue by swc132994** [jekyllgrim/Beautiful-Doom#20]
Using the alternate fire for the Super Shotgun frequently leads to monster gibbing, even at a distance. 
The primary fire may or may not gib a monster even in close proximity.

**Comment by jekyllgrim** [comment]
Which version are you using?

**Comment by swc132994** [comment]
Downloaded the git-hub master version on the 24/04/2020

**Comment by jekyllgrim** [comment]
I just pushed a fix for the enhanced chainsaw attack, thanks for pointing it out.

As for SSG gibbing, it's not relevant which type of attack you use currently, it's only about how many pellets hit a monster. However, if you fir 20 pellets in the direction of a monster, but only 3 would be enough to kill it at its current health, the other 17 will simply miss and will not be counted towards the total damage value. 
I'm considering reworking this system so that it'll count the damage before actually dealing it, so that gibbing is based on how many pellets _would_ hit a monster before killing it. With the current system, however, there are no bugs.
