### ISSUE TITLE
Doesn't work with the first episode of Ultimate DOOM

### ISSUE THREAD

**Issue by Tasosgemah** [jekyllgrim/Beautiful-Doom#42]
It loads when i try other episodes ot DOOM 2. But not the first episode of DOOM 1/Ultimate DOOM.

Using the latest version from the releases section and the latest version of gzDOOM

**Comment by jekyllgrim** [comment]
Please provide the following:

1. What exactly is wrong (observable issues, error messages, if any, etc.)
2. The exact version of GZDoom you're using
3. What other mods you have loaded with Beautiful Doom, if any
4. The contents of your GZDoom autoload folder, if any
5. Steps to reproduce, if the issue is not easily observable

**Comment by Tasosgemah** [comment]
GZDoom 4.5.0. 

I have no other mods.

I figured out what was wrong though. I used the .pk3 file from the "releases" section. When i downloaded the zip file from the "code" button, the mod works fine.
