### ISSUE TITLE
How to change the explosion effects?

### ISSUE THREAD

**Issue by Tasosgemah** [jekyllgrim/Beautiful-Doom#43]
By default, the mod uses some realistic  explosions that don't really fit into the game's overall look. I searched the texture folders and i noticed there are several different explosion effects, including a smoother version of the original (from smooth-doom perhaps)?

In the option menu there is no way to select which ones you want. Is there any other way?

Also, when you disable decorations, the barrel explosion doesn't complete it's animation. It looks weird in-game but in the folders i can see a more complete set of explosion frames.

**Comment by jekyllgrim** [comment]
There is no built-in way to change visuals of various special effects. This is likely not going to be added, since the relevance of such a feature would be relatively low and it'd lead to further option bloat, which I'm actively trying to avoid. Sorry.

You can do a personal modification to replace explosions by editing the zscript files that define which graphics is used. That'd be **w_rocketlauncher.zc** (see `BD_Rocket`, `BD_ModernRocket` and `BD_ModernGrenade` classes), and **o_misc.zc** (`BD_ExplosiveBarrel` class). You'll need [SLADE](https://slade.mancubus.net/index.php?page=downloads) to edit the pk3 archive with the mod (or, if you're keeping it unpacked, you can edit the files with any text editor). 

Since this is technically not a bug or an issue, I suggest joining my discord channel for general questions and discussion: https://discord.gg/MJGdYjk.

**Comment by Tasosgemah** [comment]
I tried the discord but i don't have permission to do any posts.

Thanks anyway. Editing those files seem way over my head =(
