### ISSUE TITLE
Fists and Assault Rifle weapon icons

### ISSUE THREAD

**Issue by mmaulwurff** [jekyllgrim/Beautiful-Doom#49]
**GZDoom** 4.5.0
**Map:** any
**Other mods:** Gearbox
**Error:** none
**Description:** Some mods like Gearbox and PyWheaponWheel display weapon icons. Fists, however, lack an icon, and Assault Rifle displays Chaingun icon (the tag for Assault Rifle changes with if modern weapons are chosen, nice touch!).

I'm not sure if it's okay to ask for these, because players won't see these additional graphics unless they load specific other mods alongside Beautiful Doom, and everything functions fine even without icons.

![Screenshot_Doom_20210319_204247](https://user-images.githubusercontent.com/742823/111789911-3c4cdc80-88f4-11eb-89bb-a1149b6b8b70.png)

**Comment by jekyllgrim** [comment]
Thanks for pointing it out, that's fair. Thankfully, Gearbox uses inventory.icon, if it's present, so this is something I'll be able to define dynamically. I'll have to solve a semi-related problem where sometimes some vanilla weapons will appear in your inventory after using "give all", however; then I'll make a commit with a fix.

**Comment by jekyllgrim** [comment]
Fixed in the most recent commit. Please refer to [this](https://github.com/jekyllgrim/Beautiful-Doom#how-to-play-the-freshest-dev-build) to learn how to download a dev build of the mod. It should also prevent duplicate weapons from appearing when using cheats, getting weapons via ACS, and such.

Gearbox works, PyWeaponWheel doesn't because it doesn't use inventory icons, apparently.
