### ISSUE TITLE
[Suggestion] Optimize loading of saved games (GZDoom)

### ISSUE THREAD

**Issue by d0vgan** [jekyllgrim/Beautiful-Doom#55]
While playing with Beautiful Doom 7.1.6 in GZDoom 4.6.1, each loading of a saved game takes about 10..15 seconds.
It applies to playing a pure DOOM/DOOM2 as well as to playing DOOM2 with different modes.
You may say that 10..15 seconds is a fair time, but here is why I'm raising this question.
Recently I tried a build of Project Brutality 3.0 that takes forever to be loaded (a few _minutes_ to load the first level of DOOM2!!!) - and I was surprised that its saved games are loaded _instantly_!
So I'm wondering whether it uses some technique (maybe caching?) that might be adapted to Beautiful Doom to increase its load game performance?

**Comment by jekyllgrim** [comment]
I've not been able to reproduce this. The only relatively slow loadtime I have is when GZDoom is first launched with Beautiful Doom—which happens because multiple classes get precached.

Please do the following:
- Update to a current version of GZDoom (4.7.0 or a fresher dev build)
- Make sure **Precache GL Textures** is enabled (Options > Display Options > Texture Options)

Aside from that, there's nothing obvious I can really do, because—well, see Doom2fan's message. It's safe to say that it's not a general issue, I've not received any reports like this.

**Comment by d0vgan** [comment]
Well, it looks like these options within "gzdoom.ini":
```
gl_texture_hqresizemode=3
gl_texture_hqresizemult=4
```
make the saved games of Beautiful Doom 7.1.6 (either playing pure DOOM2 or with mods) to load for 10..15 seconds!
Whereas these options:
```
gl_texture_hqresizemode=0
gl_texture_hqresizemult=1
```
make the saved games of Beautiful Doom 7.1.6 to load instantly!

The question is: 
What can be the underlying cause of it??
